### ISSUE TITLE
More fasttext Embedding information ?

### ISSUE THREAD

**Issue by antoinecomp** [Ram81/Toxic-Comment-Classification#1]
Hi Ram !

I tried to test your code yet I didn't understood what you use in `f = codecs.open('../input/fasttext/wiki.simple1.vec', encoding='utf-8')`. May you provide more infromation about it ?

I've understood it is a  pre-trained word vectors for 294 languages, but I don't know how to download it.

Did you tried to download it from [fastText wiki word vectors page](https://fasttext.cc/docs/en/pretrained-vectors.html)? Because this file name is wiki.simple.vec whereas yours is wiki.simple1.vec

**Comment by antoinecomp** [comment]
Okay, the answer is to download the pre-trained vector I pointed out above and change its name in Ram's code

**Comment by Ram81** [comment]
@antoinecomp Thanks
